# ç½‘ç«™çš„åŸºæœ¬ä¿¡æ¯
site:
  tab: å¯’æŸ³åˆ«è‹‘ # æµè§ˆå™¨æ ‡ç­¾æ ä¸Šæ˜¾ç¤ºçš„æ–‡æœ¬
  title: ğŸ’  å¯’æŸ³åˆ«è‹‘ # ç½‘ç«™çš„æ ‡é¢˜
  description: æŸ³å«çŸ¥å‘æŒ¥æƒ³è±¡åŠ›å’Œåˆ›é€ åŠ›çš„èµ›åšåèŠ±å›­ # ç½‘ç«™çš„æè¿°ï¼Œç”¨äºSEOç­‰
  language: zh-CN # ğŸŒŸ å…³é”®ï¼šå‘Šè¯‰æµè§ˆå™¨è¿™æ˜¯ä¸€ä¸ªç®€ä½“ä¸­æ–‡ç½‘ç«™
  favicon: /favicon.ico # ç½‘ç«™çš„å›¾æ ‡ï¼Œç”¨äºæµè§ˆå™¨æ ‡ç­¾æ å’Œå…¶ä»–åœ°æ–¹æ˜¾ç¤º
  theme: # æ›´å¤šä¸»é¢˜ https://daisyui.com/docs/themes/
    light: winter # ä¸»é¢˜çš„æµ…è‰²æ¨¡å¼
    dark: dracula # ä¸»é¢˜çš„æ·±è‰²æ¨¡å¼
    code: github-dark # ä»£ç å—çš„ä¸»é¢˜ https://expressive-code.com/guides/themes/
  date_format: YYYYå¹´MMæœˆDDæ—¥ # ğŸŒŸ æ—¥æœŸæ ¼å¼ä¹Ÿæ”¹æˆäº†ä¸­æ–‡ä¹ æƒ¯
  blog: # åšå®¢ç›¸å…³é…ç½®
    pageSize: 8 # æ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°é‡
  menu: # èœå•é…ç½®
    - id: home 
      text: é¦–é¡µ # æ±‰åŒ–
      href: / 
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: å±…å£«è‡ªåº # æ±‰åŒ–
      href: /about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: blog
      text: åšå®¢ # æ±‰åŒ–
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
      subItems:
        - id: all
          text: å…¨éƒ¨æ–‡ç«  # æ±‰åŒ–
          href: /blog
          svg: "material-symbols:ink-pen-outline-rounded"
          target: _self
        - id: documentation
          text: å­¦ä¹ æ–‡æ¡£ # æ±‰åŒ–
          href: /blog/category/Documentation
          svg: "material-symbols:unknown-document-outline-rounded"
          target: _self
        - id: examples
          text: ä»£ç ç¤ºä¾‹ # æ±‰åŒ–
          href: /blog/category/Examples
          svg: "material-symbols:deployed-code-outline"
          target: _self
    - id: project
      text: å®éªŒå®¤é¡¹ç›® # æ±‰åŒ–
      href: /project
      svg: "material-symbols:code-blocks-outline"
      target: _self
    - id: friend
      text: å‹é“¾ # æ±‰åŒ–
      href: /friend
      svg: "material-symbols:supervisor-account-outline-rounded"
      target: _self
    - id: contact
      text: è”ç³»æˆ‘ # æ±‰åŒ–
      href: "mailto:contact.evesunmaple@outlook.com"
      target: _blank # åœ¨æ–°æ ‡ç­¾é¡µæ‰“å¼€
      svg: "material-symbols:attach-email-outline-rounded"

# ç”¨æˆ·çš„ä¸ªäººä¿¡æ¯
user:
  name: æŸ³å«çŸ¥ # æ›¿æ¢æˆäº†ä½ çš„æ˜µç§°
  site: "https://zylatent.com" # ç­‰ä»¥åé…å¥½äº†å†æ¢æˆä½ è‡ªå·±çš„åŸŸå
  avatar: /avatar.jpg # ç”¨æˆ·å¤´åƒè·¯å¾„
  sidebar: # ä¾§è¾¹æ é…ç½®
    social:
      - href: "https://afdian.com/a/saroprock" 
        ariaLabel: èµåŠ©æ”¯æŒ # æ±‰åŒ–ï¼šå›¾æ ‡çš„å¯è®¿é—®æ€§æ ‡ç­¾
        title: èµåŠ©æ”¯æŒ # æ±‰åŒ–ï¼šå›¾æ ‡çš„æ‚¬æµ®æ ‡é¢˜
        svg: "ri:cup-line"
      - href: "https://github.com/EveSunMaple"
        ariaLabel: GitHubä¸»é¡µ # æ±‰åŒ–
        title: GitHubä¸»é¡µ # æ±‰åŒ–
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/438392347"
        ariaLabel: å“”å“©å“”å“© # æ±‰åŒ–
        title: å“”å“©å“”å“© # æ±‰åŒ–
        svg: "ri:bilibili-line"
      - href: "https://x.com/EveSunMaple"
        ariaLabel: X(æ¨ç‰¹) # æ±‰åŒ–
        title: X(æ¨ç‰¹) # æ±‰åŒ–
        svg: "ri:twitter-line"
  footer:
    social:
      - href: "https://afdian.com/a/saroprock" 
        ariaLabel: èµåŠ©æ”¯æŒ 
        title: èµåŠ©æ”¯æŒ 
        svg: "ri:cup-line"
      - href: "https://github.com/EveSunMaple"
        ariaLabel: GitHubä¸»é¡µ 
        title: GitHubä¸»é¡µ 
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/438392347"
        ariaLabel: å“”å“©å“”å“© 
        title: å“”å“©å“”å“© 
        svg: "ri:bilibili-line"
      - href: "https://x.com/EveSunMaple"
        ariaLabel: X(æ¨ç‰¹) 
        title: X(æ¨ç‰¹) 
        svg: "ri:twitter-line"